name: Matrix Echo Workflow

on: [push]

jobs:
  echo-job:
    timeout-minutes: 15
    runs-on: warpdev-ubuntu-latest-amd64-4x
    strategy:
      fail-fast: false
      matrix:
        node-version: [20.x]
        shard: [1,2,3,4,5,6,7,8,9,10]

    env:
      NODE_OPTIONS: "--max-old-space-size=14336"

    steps:
      - name: Echo Hello World
        run: echo Hello World
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile --prefer-offline
